services:
  vibe-kanban:
    container-name: "vibe-kanban"
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
      - ./repos:/repos
    env_file:
      - .env
    restart: unless-stopped
